### ISSUE TITLE
parts_linkers.csv must contain 3 columns

### ISSUE THREAD

**Issue by hainesm6** [BASIC-DNA-ASSEMBLY/DNA-BOT#12]
# Issue
Often when making a parts_linkers.csv file you leave off part concentration. This can lead to 2 columns rather than 3.

# Current behaviour
Will throw and error in line 286 of [dnabot_app.py](DNA-BOT/dnabot/dnabot_app.py) otherwise.

# Desired behaviour
Tollerate rows containing 2 columns.

**Comment by Benedict-Carling** [comment]
Hello 👋, I have been working with DNA-BOT as part of imperial iGEM, i would like to work on this issue, may i be assigned if its still open/active? Thanks Ben

**Comment by hainesm6** [comment]
Hi @Benedict-Carling. Yes feel free to contribute. All are welcome to :smiley: Just raise a pull request and someone will take a look.

**Comment by hainesm6** [comment]
fixed by #13
